### ISSUE TITLE
Highlighting stops in weird conditions

### ISSUE THREAD

**Issue by Aurel300** [vshaxe/haxe-TmLanguage#47] opened 2019-07-21 19:30 UTC
```haxe
class Foo {
  function func() {
    switch x {
      case _:
        new X(Y(function () foo));
      case A({a: _}, _):
        // highlighting is broken at this point
        new Map<String, String>();
        trace("foobar");
        var x = 1 + 2;
        var etc = "etc";
    }
  }
}
```

It seems the lines with `new X` and `case A` are both required for the issue to happen. Can be alleviated by putting `foo` inside `{}`.

**Comment by Gama11** [comment] 2019-07-21 20:58
Seems like a duplicate of https://github.com/vshaxe/haxe-TmLanguage/issues/3.

**Closed as completed by Gama11** 2019-07-21 20:58 UTC
