### ISSUE TITLE
Complex compiler conditionals

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/haxe-TmLanguage#20] opened 2017-03-07 14:40 UTC
<img width="709" alt="screen shot 2017-03-07 at 10 38 45 pm" src="https://cloud.githubusercontent.com/assets/1103788/23661223/094670f4-0387-11e7-8626-0d5f9c3fd228.png">

```haxe
#elseif (!no_ssl && (hxssl || hl || cpp || (neko && !(macro || interp)))) new sys.ssl.Socket();
```

Note the last two closing parenthesis.

**Comment by Gama11** [comment] 2017-03-07 15:25
Pretty sure this is a duplicate of #5.

**Closed as completed by Gama11** 2017-03-07 15:25 UTC
Labels: duplicate
